import { SeedLesson, q, s } from './lessonHelpers';

export const LESSONS_1: SeedLesson[] = [
  {
    key: 'sort_your_waste',
    title: 'Why Sorting Your Waste Matters',
    emoji: '🗑️',
    tag: 'Waste',
    summary: 'Wet, dry and hazardous: the three-bin habit that makes recycling and composting possible.',
    readMinutes: 3,
    sections: [
      s('The three bins', 'India\'s Solid Waste Management Rules, 2016 ask households to separate waste at the source into three streams: wet waste (food scraps, peels, garden leaves), dry waste (paper, plastic, glass, metal, cloth) and domestic hazardous waste (batteries, bulbs, expired medicines, paint, sanitary and similar items).'),
      s('Why mixing ruins it', 'Once a banana peel soaks a newspaper or a battery lands in a food bin, the whole load becomes hard to recycle or compost. Mixed waste mostly ends up in landfills and dumps, where rotting food releases methane, a powerful greenhouse gas, and chemicals can seep into soil and water.'),
      s('What sorting makes possible', 'Clean dry waste can be sold to recyclers and gives waste pickers a better income. Wet waste can become compost for gardens and parks. Roughly half or more of household waste in Indian cities is organic, so separating it is the single biggest win.'),
    ],
    takeaway: 'Keep wet, dry and hazardous waste apart at home, because mixing is what turns useful material into rubbish.',
    quiz: [
      q('How many waste streams do the 2016 rules ask households to separate?', 'Three', ['One', 'Two', 'Six'], 'Wet, dry and domestic hazardous waste are the three streams.'),
      q('Which of these belongs in the wet waste bin?', 'Vegetable peels', ['Used batteries', 'A glass bottle', 'A plastic wrapper'], 'Food scraps and garden waste are wet waste.'),
      q('What gas do rotting food scraps release in a landfill?', 'Methane', ['Helium', 'Oxygen', 'Neon'], 'Landfilled food waste breaks down without air and produces methane.'),
      q('Where should expired medicines go?', 'The hazardous waste stream', ['The wet waste bin', 'Down the sink', 'Into the garden soil'], 'Medicines are hazardous and should not be mixed with ordinary waste or poured away.'),
      q('Why does mixing waste cause problems?', 'It makes recycling and composting much harder', ['It makes waste weigh less', 'It makes waste decompose faster', 'It has no effect'], 'Contaminated material is hard to recycle or compost, so more of it is dumped.'),
    ],
    sourceNote: 'Solid Waste Management Rules, 2016 (Government of India).',
  },
  {
    key: 'plastic_bag_truth',
    title: 'The Real Life of a Plastic Bag',
    emoji: '🛍️',
    tag: 'Waste',
    summary: 'Used for minutes, around for centuries: what happens after you say "no bag needed".',
    readMinutes: 3,
    sections: [
      s('Minutes of use, centuries of waste', 'A carry bag is often used for a few minutes, yet plastic does not truly rot. Sunlight and weather break it into smaller and smaller pieces rather than making it disappear, and estimates for how long this takes run into hundreds of years.'),
      s('Where bags actually end up', 'Light bags blow out of overflowing bins and open dumps. They clog drains, which makes urban flooding worse, and they get eaten by stray cattle and wildlife that mistake them for food. Once in rivers, they travel all the way to the sea.'),
      s('What the rules say', 'India has raised the minimum thickness of plastic carry bags in steps, to 120 microns from the end of 2022, because very thin bags are rarely reused or collected. A bag that is thick and reused many times is better than a thin one used once, but a cloth or jute bag you already own is best of all.'),
    ],
    takeaway: 'Keep a foldable bag in your pocket or scooter, and refuse a new bag when you only need to carry one or two things.',
    quiz: [
      q('What usually happens to plastic over time?', 'It breaks into smaller pieces', ['It turns into soil', 'It becomes food for plants', 'It disappears in a year'], 'Plastic fragments rather than fully breaking down, creating microplastics.'),
      q('How can discarded bags make city floods worse?', 'By blocking drains', ['By heating the air', 'By absorbing water', 'By making rain heavier'], 'Choked drains cannot carry away monsoon rain.'),
      q('Why are very thin bags a bigger problem?', 'They are rarely reused or collected', ['They are too heavy', 'They cost more', 'They only break at night'], 'Thin bags tend to be used once and then escape the waste system.'),
      q('Which is the best choice for most shopping trips?', 'A reusable cloth or jute bag', ['A new thin plastic bag each time', 'Two bags for each item', 'A paper cup'], 'A bag you already own and reuse avoids creating new waste.'),
      q('Which animals are often harmed by eating loose plastic bags?', 'Cattle and wildlife', ['Only birds in zoos', 'Only pets', 'No animals at all'], 'Animals can mistake bags for food, which can block their stomachs.'),
    ],
    sourceNote: 'Plastic Waste Management Amendment Rules, 2021 (Government of India); general plastics research.',
  },
  {
    key: 'hidden_water',
    title: 'The Hidden Water in Everyday Things',
    emoji: '💧',
    tag: 'Water',
    summary: 'Your food and clothes use far more water than your taps do.',
    readMinutes: 3,
    sections: [
      s('Water you never see', 'Your "water footprint" is not just what comes out of the tap. It includes the water used to grow, process and transport everything you eat and wear. Most of a person\'s water use is hidden inside products.'),
      s('Some examples', 'Widely cited estimates say a cotton T-shirt takes about 2,700 litres of water to make, a kilogram of rice roughly 2,500 litres, and a kilogram of beef around 15,000 litres. Vegetables, pulses and millets generally need far less.'),
      s('What you can do', 'Wearing clothes for longer, wasting less food and eating more pulses, millets and vegetables all cut your hidden water use. At home, fixing a dripping tap, running full washing loads and reusing RO reject water for cleaning also add up.'),
    ],
    takeaway: 'Wasting food or clothes wastes the water that made them, so using things for longer is a water-saving habit.',
    quiz: [
      q('What does a "water footprint" include?', 'Water used to make everything you use', ['Only tap water', 'Only drinking water', 'Only rainwater'], 'It counts the hidden water in food, clothes and other products.'),
      q('Which usually needs the most water per kilogram?', 'Beef', ['Vegetables', 'Pulses', 'Millets'], 'Meat, especially beef, has a very large water footprint.'),
      q('Roughly how much water is cited for making one cotton T-shirt?', 'About 2,700 litres', ['About 2 litres', 'About 27 litres', 'About 270 litres'], 'This commonly cited estimate includes growing the cotton.'),
      q('Which habit saves hidden water?', 'Wearing clothes for longer', ['Buying a new outfit each week', 'Leaving taps dripping', 'Throwing away leftovers'], 'Longer use means fewer new items need to be made.'),
      q('What can reject water from an RO purifier be reused for?', 'Mopping or cleaning', ['Drinking', 'Cooking', 'Baby formula'], 'It is not for drinking but is fine for cleaning or watering.'),
    ],
    sourceNote: 'Water Footprint Network and WWF commonly cited estimates; figures vary by region and method.',
  },
  {
    key: 'catch_the_rain',
    title: 'Catching the Monsoon: Rainwater Harvesting',
    emoji: '🌧️',
    tag: 'Water',
    summary: 'Most of India\'s rain falls in four months. Here is how to keep some of it.',
    readMinutes: 3,
    sections: [
      s('Four months of plenty', 'A large part of India\'s yearly rainfall, roughly three-quarters, arrives in the monsoon months from June to September. Much of it runs off paved ground into drains and rivers, while groundwater levels in many places keep falling.'),
      s('Two simple ways to harvest', 'Rooftop harvesting guides rain from a roof through a pipe and filter into a tank for storage, or into a recharge pit or borewell that tops up groundwater. Even a small house terrace can collect thousands of litres in a good monsoon.'),
      s('Why it matters', 'India is the world\'s largest user of groundwater, and in many cities the water table is dropping every year. Recharging it, along with letting rain soak into the ground through open soil and permeable paving, protects wells and borewells in the dry months.'),
    ],
    takeaway: 'Letting rain soak in, or storing it from your roof, turns a few weeks of flood into months of water security.',
    quiz: [
      q('When does most of India\'s yearly rain fall?', 'June to September', ['December to February', 'March to April', 'All year equally'], 'The southwest monsoon brings the bulk of the rain.'),
      q('What does rooftop harvesting collect?', 'Rain falling on a roof', ['Dew from grass', 'River water', 'Sea water'], 'Roof water is guided through pipes into storage or a recharge pit.'),
      q('What is a recharge pit for?', 'Topping up groundwater', ['Burning waste', 'Growing crops', 'Cooling the roof'], 'It lets rain seep down into the soil and aquifer.'),
      q('Which country uses the most groundwater in the world?', 'India', ['Iceland', 'Norway', 'Japan'], 'India extracts more groundwater than any other country.'),
      q('Why does paved ground make flooding worse?', 'Rain cannot soak in and runs off', ['It attracts more rain', 'It makes rain colder', 'It dries water instantly'], 'Runoff overwhelms drains instead of recharging the ground.'),
    ],
    sourceNote: 'India Meteorological Department monsoon climatology; Central Ground Water Board.',
  },
  {
    key: 'vampire_power',
    title: 'Vampire Power and Star Labels',
    emoji: '🔌',
    tag: 'Energy',
    summary: 'Gadgets that "sleep" still sip electricity. Learn to cut it and to read energy labels.',
    readMinutes: 3,
    sections: [
      s('Always on, quietly', 'TVs, set-top boxes, chargers, microwaves and routers keep drawing power even when you are not using them. This "standby" or "vampire" power is often estimated at around 5 to 10 percent of a home\'s electricity use.'),
      s('Easy fixes', 'Switch appliances off at the plug, use a power strip with a switch for the TV corner, and unplug chargers when they are not in use. Switching to LED bulbs is another quick win: LEDs use at least 75 percent less energy than old filament bulbs.'),
      s('Reading the star label', 'Many appliances in India carry a Bureau of Energy Efficiency (BEE) star label from 1 to 5. More stars mean the appliance uses less electricity for the same job. A 5-star fridge or AC often costs more up front but saves money on bills over the years.'),
    ],
    takeaway: 'Switch off at the plug, choose LEDs, and compare star labels before you buy an appliance.',
    quiz: [
      q('What is "vampire power"?', 'Electricity used by devices on standby', ['Power from solar panels', 'Power from batteries only', 'Power cuts'], 'Devices plugged in but not in use still draw electricity.'),
      q('How many stars is the best BEE rating?', '5', ['1', '3', '10'], 'Five stars means the most efficient.'),
      q('How much less energy do LEDs use than old filament bulbs?', 'At least 75 percent less', ['About the same', '10 percent less', '5 percent more'], 'LEDs are far more efficient, which cuts bills and emissions.'),
      q('Which action cuts standby power?', 'Unplugging chargers not in use', ['Leaving the TV on mute', 'Buying a bigger TV', 'Using more extension cords'], 'No plug, no standby draw.'),
      q('Why can a 5-star appliance be worth a higher price?', 'It saves on electricity bills over time', ['It never needs repair', 'It uses no electricity', 'It lasts exactly 50 years'], 'Lower running costs usually repay the extra cost.'),
    ],
    sourceNote: 'Bureau of Energy Efficiency (BEE) star labelling programme; US Department of Energy on LED efficiency.',
  },
  {
    key: 'food_waste',
    title: 'Food Waste: From Plate to Planet',
    emoji: '🍛',
    tag: 'Food',
    summary: 'Wasted food is wasted land, water, money and a source of methane.',
    readMinutes: 3,
    sections: [
      s('A big number', 'The UN Environment Programme estimates that around 17 percent of the food available to consumers worldwide is wasted, and households are responsible for the largest share, around 60 percent of that waste, more than shops or restaurants.'),
      s('Why it hurts the climate', 'When food is thrown away, all the land, water, fertiliser and fuel used to produce it are wasted too. Food that rots in a landfill gives off methane. Cutting food waste is among the most effective everyday climate actions.'),
      s('How to waste less', 'Plan meals, store vegetables properly, cook only what you will eat, and use leftovers creatively. Understand the difference between "best before" and "use by", because many foods are safe after the best-before date. Compost the scraps you cannot avoid.'),
    ],
    takeaway: 'Plan, store and cook just enough, and compost what is left: fixing food waste starts in the home kitchen.',
    quiz: [
      q('Which group wastes the largest share of food worldwide?', 'Households', ['Farmers only', 'Airlines', 'Schools only'], 'UNEP finds households account for most food waste.'),
      q('What gas do rotting food scraps give off in landfills?', 'Methane', ['Helium', 'Oxygen', 'Hydrogen'], 'Methane is a potent greenhouse gas.'),
      q('What else is wasted when food is thrown away?', 'Water, land and energy used to produce it', ['Only the packaging', 'Nothing else', 'Only the money'], 'Producing food uses many resources.'),
      q('Which habit reduces household food waste?', 'Planning meals before shopping', ['Buying extra in bulk every day', 'Cooking double always', 'Never using leftovers'], 'A plan prevents over-buying and spoilage.'),
      q('What can you do with unavoidable food scraps?', 'Compost them', ['Pour them into drains', 'Burn them', 'Bury plastic with them'], 'Composting returns nutrients to the soil.'),
    ],
    sourceNote: 'UNEP Food Waste Index Report 2021.',
  },
  {
    key: 'know_your_aqi',
    title: 'Reading the Air Quality Index',
    emoji: '🌫️',
    tag: 'Air',
    summary: 'What the colours and numbers mean, and what to do on a bad air day.',
    readMinutes: 3,
    sections: [
      s('One number for the air', 'The Air Quality Index (AQI) turns several pollutants into a single number. India\'s scale runs from 0 to 500: Good (0 to 50), Satisfactory (51 to 100), Moderate (101 to 200), Poor (201 to 300), Very Poor (301 to 400) and Severe (401 to 500).'),
      s('What is PM2.5?', 'PM2.5 means particles smaller than 2.5 micrometres, far thinner than a human hair. They come from vehicles, construction dust, burning of waste and crop residue, and industry. They are small enough to go deep into the lungs and even enter the bloodstream.'),
      s('On a bad air day', 'Check the AQI before outdoor exercise, move workouts indoors when air is Poor or worse, and keep windows closed during the worst hours. A well-fitted N95-type mask helps outdoors; ordinary cloth masks do much less against fine particles. Never burn leaves or rubbish.'),
    ],
    takeaway: 'Check the AQI like you check the weather, and avoid adding smoke by never burning waste.',
    quiz: [
      q('What is the AQI scale range used in India?', '0 to 500', ['0 to 10', '0 to 100 only', '1 to 5'], 'Higher numbers mean worse air.'),
      q('What does PM2.5 refer to?', 'Particles smaller than 2.5 micrometres', ['Pollution measured at 2.5 pm', 'Pesticide mix 2.5', 'A type of petrol'], 'These fine particles reach deep into the lungs.'),
      q('An AQI of 350 falls in which category?', 'Very Poor', ['Good', 'Satisfactory', 'Moderate'], '301 to 400 is Very Poor.'),
      q('What is a sensible choice on a Severe AQI day?', 'Exercise indoors', ['Run outdoors', 'Burn leaves to warm up', 'Open all windows'], 'Reducing exposure is the main protection.'),
      q('Which action adds to air pollution?', 'Burning garden waste or rubbish', ['Carpooling', 'Using a bicycle', 'Walking short trips'], 'Open burning releases large amounts of fine particles.'),
    ],
    sourceNote: 'Central Pollution Control Board (CPCB), National Air Quality Index.',
  },
  {
    key: 'single_use_plastics',
    title: 'Single-Use Plastics: What Is Banned and Why',
    emoji: '🥤',
    tag: 'Waste',
    summary: 'India restricted many throwaway plastic items in 2022. Know the list and the easy swaps.',
    readMinutes: 3,
    sections: [
      s('The 2022 ban', 'From 1 July 2022, India banned the manufacture, sale and use of a list of identified single-use plastic items that are low in use but high in littering. These include plastic sticks for earbuds, balloons and candy, plastic plates, cups, glasses, cutlery, straws, trays, stirrers, and thermocol (polystyrene) used for decoration.'),
      s('Why these items?', 'Items like straws and cutlery are used for minutes, are too light and dirty to be recycled easily, and end up in drains, rivers and farmland. They are also easy to replace with reusable or biodegradable alternatives.'),
      s('Easy swaps', 'Carry a steel bottle and a small cutlery set, say no to the straw, ask for tea in a kulhad or your own cup, and bring a tiffin box for takeaway food. Small refusals repeated daily keep thousands of items out of the waste stream.'),
    ],
    takeaway: 'Refuse the throwaway item first: a reusable bottle, cup and box replace most banned items.',
    quiz: [
      q('When did India\'s ban on identified single-use plastics start?', '1 July 2022', ['1 January 2000', '15 August 2010', '5 June 2030'], 'The ban on identified items took effect on 1 July 2022.'),
      q('Which of these is covered by the ban?', 'Plastic straws', ['Steel straws', 'Glass bottles', 'Cloth bags'], 'Plastic straws and cutlery were on the list.'),
      q('Why were these items chosen?', 'Low usefulness but high littering', ['They are expensive', 'They are very heavy', 'They are made from wood'], 'They are used briefly and rarely recycled.'),
      q('Which is a good swap for a plastic cup?', 'Your own reusable cup or a kulhad', ['Two plastic cups', 'A thermocol cup', 'A plastic bag'], 'Reusable or natural options avoid waste.'),
      q('What is the first and best step with single-use items?', 'Refuse them', ['Bury them', 'Burn them', 'Hide them in the bin'], 'Refusing prevents waste altogether.'),
    ],
    sourceNote: 'Plastic Waste Management (Amendment) Rules, 2021; Ministry of Environment, Forest and Climate Change.',
  },
  {
    key: 'home_composting',
    title: 'Compost at Home in Four Steps',
    emoji: '🪱',
    tag: 'Waste',
    summary: 'Turn kitchen scraps into dark, crumbly soil food, even on a balcony.',
    readMinutes: 3,
    sections: [
      s('Greens and browns', 'Compost needs a balance of "greens" (wet, nitrogen-rich waste like vegetable peels and tea leaves) and "browns" (dry, carbon-rich material like dry leaves, shredded paper and cardboard). Aim for roughly two parts brown to one part green so it does not turn smelly and slimy.'),
      s('Four steps', 'Pick a bin or pot with holes for air. Add a layer of browns, then your kitchen scraps, then cover with more browns. Keep it damp like a squeezed sponge. Turn it every week or so to bring in air. In a few weeks to a few months you will have dark, earthy compost.'),
      s('What to avoid', 'Skip meat, fish, dairy, cooked oily food and pet waste in a home bin, as they smell and attract pests. Citrus and onion are fine in small amounts. If it smells bad, add more dry material and mix in air.'),
    ],
    takeaway: 'Balance wet scraps with dry leaves or paper, keep it airy and damp, and avoid meat and dairy.',
    quiz: [
      q('What are "browns" in composting?', 'Dry, carbon-rich material like dry leaves', ['Wet vegetable peels', 'Meat scraps', 'Plastic'], 'Browns balance the wet greens and keep air flowing.'),
      q('What should compost feel like?', 'Damp like a squeezed sponge', ['Soaking wet', 'Bone dry', 'Hot and sticky'], 'Moist but not dripping is right.'),
      q('Which item should stay out of a home compost bin?', 'Meat and dairy', ['Tea leaves', 'Vegetable peels', 'Dry leaves'], 'They smell and attract pests.'),
      q('Why turn the compost regularly?', 'To bring in air', ['To make it heavier', 'To dry it fully', 'To add plastic'], 'Air helps the right microbes break the waste down.'),
      q('What should you do if your compost smells bad?', 'Add dry material and mix in air', ['Add more wet scraps', 'Seal it tightly', 'Add meat'], 'Browns and air restore the balance.'),
    ],
    sourceNote: 'Standard home-composting guidance used by municipal waste programmes.',
  },
  {
    key: 'move_smarter',
    title: 'Getting Around with Less Carbon',
    emoji: '🚌',
    tag: 'Travel',
    summary: 'Buses, metros, bikes and shared rides: the transport choices that matter most.',
    readMinutes: 3,
    sections: [
      s('Why transport matters', 'Transport is one of the largest sources of greenhouse gases and also a major source of the fine particles that make city air unhealthy. Most emissions come from petrol and diesel vehicles carrying one or two people.'),
      s('Sharing the ride', 'A full bus or metro carries many people for a fraction of the emissions per person compared with cars. Carpooling and shared autos do the same on a smaller scale. For short trips, walking or cycling is zero-emission and also good for health.'),
      s('Smaller changes still count', 'Combine errands into one trip, keep tyres properly inflated, switch the engine off at long red lights, and consider an electric two-wheeler or CNG vehicle for daily use. Working from home even one day a week cuts a surprising number of kilometres.'),
    ],
    takeaway: 'Fewer solo car trips, more shared or active journeys: even one habit changed saves emissions every week.',
    quiz: [
      q('Why is a full bus often better for the climate than a car?', 'It carries many people per trip', ['It is quieter', 'It is slower', 'It uses no fuel'], 'Emissions are shared across many passengers.'),
      q('Which type of trip is best for walking or cycling?', 'Short trips', ['Long highway trips only', 'Trips with heavy luggage only', 'None'], 'Short trips are easiest to do without a vehicle.'),
      q('What does carpooling do?', 'Reduces the number of vehicles on the road', ['Makes fuel free', 'Doubles emissions', 'Replaces tyres'], 'Fewer cars means lower emissions and congestion.'),
      q('Which small habit reduces fuel use?', 'Keeping tyres properly inflated', ['Driving faster', 'Idling at lights', 'Carrying extra weight'], 'Correct tyre pressure improves efficiency.'),
      q('Besides greenhouse gases, what else do vehicles emit that harms health?', 'Fine particles', ['Fresh air', 'Rainwater', 'Oxygen'], 'Exhaust adds to PM2.5 in cities.'),
    ],
    sourceNote: 'General transport-emissions guidance (IPCC, IEA summaries).',
  },
];
