import { SeedLesson, q, s } from './lessonHelpers';

export const LESSONS_3: SeedLesson[] = [
  {
    key: 'carbon_footprint_101',
    title: 'Your Carbon Footprint in Plain Words',
    emoji: '👣',
    tag: 'Climate',
    summary: 'What it means, what drives it, and which choices move the needle most.',
    readMinutes: 3,
    sections: [
      s('A running total', 'Your carbon footprint is the total greenhouse gas emissions caused by your activities, usually shown as carbon dioxide equivalent. It adds up from the electricity you use, how you travel, what you eat, what you buy and the waste you create.'),
      s('Where India stands', 'Per person, India\'s emissions are well below the world average and far below those of many wealthy countries, but the country\'s total is large because of its population, and it is growing as incomes rise. Choices made now about energy and cities will shape the future.'),
      s('The big levers', 'Four areas matter most for most households: electricity (efficient appliances, solar), transport (fewer solo car and flight trips), food (less waste, more plant-based meals) and what you buy (fewer, longer-lasting things). Fixing the biggest one first is better than worrying about many tiny ones.'),
    ],
    takeaway: 'Focus on energy, transport, food and shopping: the four areas that make up most of a footprint.',
    quiz: [
      q('What does a carbon footprint measure?', 'Greenhouse gases caused by your activities', ['The weight of your shoes', 'How much you walk', 'Your water bill'], 'It sums emissions from your lifestyle.'),
      q('Which is one of the big levers for a household?', 'Electricity use', ['The colour of your walls', 'How long you sleep', 'The brand of your pen'], 'Electricity, transport, food and shopping dominate.'),
      q('How do India\'s per-person emissions compare with the world average?', 'Well below', ['Far above', 'Exactly equal', 'Double'], 'India\'s per-capita emissions are below the global average.'),
      q('What is a sensible approach to reducing a footprint?', 'Start with the biggest sources', ['Ignore it', 'Change tiny things only', 'Do nothing until others act'], 'Targeting the largest sources gives the most impact.'),
      q('Footprints are usually shown as?', 'Carbon dioxide equivalent', ['Litres of water', 'Number of steps', 'Kilometres'], 'CO2e combines different gases into one number.'),
    ],
    sourceNote: 'Global Carbon Project and Our World in Data per-capita emissions comparisons.',
  },
  {
    key: 'spot_greenwashing',
    title: 'How to Spot Greenwashing',
    emoji: '🕵️',
    tag: 'Lifestyle',
    summary: 'When "eco" is only a label. Questions to ask before you buy.',
    readMinutes: 3,
    sections: [
      s('What it is', 'Greenwashing is when a company or product makes itself look more environmentally friendly than it really is. It might use green colours, leaf images and vague words like "eco", "natural" or "green" without proof.'),
      s('Warning signs', 'Be cautious about vague claims with no detail, claims that highlight one small benefit while ignoring a big harm, labels that look official but come from the company itself, and "biodegradable" or "compostable" claims that do not say where or how long. A product that is made less but marketed more is a red flag.'),
      s('Better questions', 'Look for specific, measurable claims, independent certification you can verify, and honest information about materials and end of life. Ask whether you need the product at all. The most sustainable choice is often buying less or choosing something you already own.'),
    ],
    takeaway: 'Specific and verified beats vague and green-coloured: ask for proof, and ask if you need it at all.',
    quiz: [
      q('What is greenwashing?', 'Exaggerating how eco-friendly something is', ['Washing clothes in cold water', 'Cleaning with green soap', 'Painting walls green'], 'It means misleading marketing about environmental benefits.'),
      q('Which is a greenwashing warning sign?', 'Vague words like "eco" with no proof', ['A clear third-party certificate', 'Detailed material information', 'Honest end-of-life advice'], 'Vague claims without evidence are suspicious.'),
      q('What type of claim is more trustworthy?', 'Specific and independently verified', ['Vague and colourful', 'Self-awarded labels', 'Only leaf pictures'], 'Verification and specifics build trust.'),
      q('Why can "biodegradable" be misleading?', 'It may only break down in special conditions', ['It always means instant', 'It always means free', 'It always means recycled'], 'Some materials need industrial composting.'),
      q('What is often the most sustainable choice?', 'Buying less', ['Buying more eco products', 'Replacing everything', 'Following every trend'], 'Avoiding unnecessary purchases beats any green label.'),
    ],
    sourceNote: 'General consumer-protection and sustainability guidance on environmental claims.',
  },
  {
    key: 'plastic_free_kitchen',
    title: 'A Plastic-Light Kitchen, One Swap at a Time',
    emoji: '🍽️',
    tag: 'Lifestyle',
    summary: 'The kitchen produces more packaging waste than any room. Easy swaps, no overhaul.',
    readMinutes: 3,
    sections: [
      s('Start with what you use up', 'Swap things as they run out rather than throwing away what works. Use steel or glass containers for storage, cloth bags for vegetables, and refill jars from the local kirana store for grains, pulses and spices instead of buying small packets.'),
      s('Cooking and heating', 'Avoid heating food in plastic containers or covering hot food with cling film, because heat can cause plastic to release chemicals into food. Choose steel, glass or ceramic for microwaving and storing hot items. Replace worn scrubbers with coconut-coir or cotton ones.'),
      s('Water and drinks', 'A filter or boiled-and-cooled water in a steel bottle replaces bottled water. Buy milk and oil from refill points when you can, carry a cloth bag to the market, and compost peels so your wet bin stays small.'),
    ],
    takeaway: 'Replace things when they wear out, and carry your own bag, bottle and containers.',
    quiz: [
      q('What is a good way to start going plastic-light?', 'Swap items as they run out', ['Throw out everything today', 'Buy all new plastic', 'Ignore packaging'], 'Gradual swaps avoid creating new waste.'),
      q('Which is better for storing hot food?', 'Steel or glass', ['Thin plastic', 'Cling film touching it', 'Paper'], 'Steel and glass are stable when hot.'),
      q('Where can you buy loose grains and pulses with less packaging?', 'The local kirana store', ['Only supermarkets', 'Only online', 'Nowhere'], 'Loose items cut single-use packets.'),
      q('What can replace a plastic dish scrubber?', 'Coconut coir', ['A plastic sponge', 'A foam pad', 'A synthetic mesh'], 'Natural scrubbers are compostable.'),
      q('What reduces bottled water use?', 'A filter and a reusable bottle', ['Buying more bottles', 'Using ice only', 'Skipping water'], 'Filtered tap water in a bottle is the usual alternative.'),
    ],
    sourceNote: 'General guidance from food-safety and waste-reduction organisations.',
  },
  {
    key: 'our_rivers',
    title: 'Why Our Rivers Struggle',
    emoji: '🏞️',
    tag: 'Water',
    summary: 'Sewage, industry, plastic and offerings: what flows in, and what citizens can do.',
    readMinutes: 3,
    sections: [
      s('What goes in', 'Rivers in many Indian cities carry untreated or partly treated sewage, industrial effluent, farm run-off, plastic waste and religious offerings. A large share of the sewage generated in cities is not fully treated before it reaches rivers, which lowers oxygen levels that fish and other life need.'),
      s('Why it matters', 'Rivers supply drinking water, irrigation, fish and livelihoods to millions of people, and many have deep cultural value. Polluted water causes disease and makes treatment for supply more costly, while foam, bad smells and fish kills are visible warnings.'),
      s('What you can do', 'Never throw rubbish, idols, flowers or plastic into rivers; use phosphate-free detergents and avoid pouring paint, oil or chemicals down drains; support or join river clean-ups; and ask your local body about sewage treatment. Reporting illegal dumping to the pollution control board helps too.'),
    ],
    takeaway: 'What goes down the drain or into the water body ends up in a river, so keep it clean at the source.',
    quiz: [
      q('What is a major source of river pollution in cities?', 'Untreated sewage', ['Clean rain', 'Fresh breezes', 'Moonlight'], 'Sewage lowers oxygen and spreads disease.'),
      q('Why does low oxygen in rivers matter?', 'Fish and other life need it', ['It makes water sweeter', 'It cools rivers', 'It has no effect'], 'Aquatic life depends on dissolved oxygen.'),
      q('Which is a good habit near rivers?', 'Not dumping flowers, idols or plastic', ['Dumping rubbish', 'Washing paint in them', 'Pouring oil in'], 'Offerings and waste add to pollution.'),
      q('Which detergent choice helps?', 'Phosphate-free', ['Extra strong chemical', 'Any with fragrance', 'Bleach only'], 'Phosphates cause algae blooms.'),
      q('Who can you report illegal dumping to?', 'The pollution control board', ['A cinema hall', 'A cricket club', 'A bookstore'], 'State pollution control boards handle such complaints.'),
    ],
    sourceNote: 'Central Pollution Control Board assessments of river water quality and sewage treatment gaps.',
  },
  {
    key: 'rooftop_solar_basics',
    title: 'Rooftop Solar, Explained',
    emoji: '☀️',
    tag: 'Energy',
    summary: 'How a home solar system works and what support is available in India.',
    readMinutes: 3,
    sections: [
      s('How it works', 'Solar panels on a roof turn sunlight into electricity. An inverter changes it into the current your home uses. With a grid-connected system, extra power goes to the grid and you get credit for it through net metering, so your bill falls.'),
      s('Why it suits India', 'Most of India receives plenty of sunshine through the year, and panels typically come with warranties of around 25 years. Solar power avoids burning coal, which cuts both greenhouse gases and air pollution, and it protects households from rising tariffs.'),
      s('Getting started', 'The government\'s PM Surya Ghar: Muft Bijli Yojana, launched in 2024, offers subsidies to help households install rooftop solar. Check with your electricity distribution company for rules, use a certified installer, make sure the roof is shaded as little as possible, and ask about maintenance and warranties.'),
    ],
    takeaway: 'A rooftop system can turn your roof into a small power plant and lower your bill for years.',
    quiz: [
      q('What does an inverter do in a solar system?', 'Converts power into usable household current', ['Stores rain', 'Cools the panels', 'Cleans the roof'], 'Panels make DC; the inverter provides AC for your home.'),
      q('What is net metering?', 'Credit for extra power sent to the grid', ['A way to read rain', 'A type of battery', 'A tax'], 'Exported power offsets your consumption.'),
      q('Roughly how long are solar panel warranties?', 'About 25 years', ['About 2 weeks', 'About 1 month', 'About 90 days'], 'Many panels are warranted for 25 years.'),
      q('Which government scheme supports rooftop solar for households?', 'PM Surya Ghar: Muft Bijli Yojana', ['PM Postal Scheme', 'Bharat Cinema Mission', 'Kisan Radio Yojana'], 'It offers subsidies for household rooftop solar.'),
      q('Why does solar help air quality?', 'It reduces coal-based electricity', ['It produces smoke', 'It burns oil', 'It adds dust'], 'Less coal burning means less pollution.'),
    ],
    sourceNote: 'Ministry of New and Renewable Energy (MNRE), PM Surya Ghar: Muft Bijli Yojana (2024).',
  },
  {
    key: 'living_with_wildlife',
    title: 'Sharing Space with Wildlife',
    emoji: '🐘',
    tag: 'Nature',
    summary: 'As forests shrink and towns grow, meetings between people and animals increase.',
    readMinutes: 3,
    sections: [
      s('Why encounters rise', 'When forests are cleared or cut by roads and farms, animals lose food, water and the routes they use to move between habitats. Elephants, leopards, monkeys and others then wander into fields and settlements, and conflict can harm both people and animals.'),
      s('Corridors and rules', 'Wildlife corridors are strips of habitat that connect forests so animals can move safely. India runs flagship programmes like Project Tiger, begun in 1973, and Project Elephant, and many protected areas and corridors. Protecting these links lowers conflict in the long run.'),
      s('Staying safe and kind', 'Never feed wild animals, since it makes them lose their fear and depend on people. Store garbage and crops securely, keep a safe distance and never chase or take selfies with wild animals, and call the forest department\'s helpline when an animal strays into a settlement.'),
    ],
    takeaway: 'Keep your distance, never feed wild animals, and protect the corridors that let them move safely.',
    quiz: [
      q('Why do wild animals enter villages and towns more often?', 'They lose habitat and food', ['They want to shop', 'They like noise', 'They are bored'], 'Habitat loss pushes animals into human areas.'),
      q('What is a wildlife corridor?', 'A habitat strip linking forests', ['A new highway', 'A hotel', 'A fence'], 'It lets animals move safely between areas.'),
      q('Which programme began in India in 1973?', 'Project Tiger', ['Project Lion Dance', 'Project Cloud', 'Project Mango'], 'Project Tiger was launched in 1973.'),
      q('What is the right response if a wild animal is near?', 'Keep distance and call the forest department', ['Feed it', 'Chase it', 'Take a selfie close up'], 'Distance keeps both people and animals safe.'),
      q('Why should you not feed wild animals?', 'They lose fear and become dependent', ['It makes them sleepy', 'It cures them', 'It helps them fly'], 'Feeding changes natural behaviour and raises conflict.'),
    ],
    sourceNote: 'National Tiger Conservation Authority; Ministry of Environment, Forest and Climate Change.',
  },
  {
    key: 'fast_fashion',
    title: 'The Hidden Cost of Cheap Clothes',
    emoji: '👕',
    tag: 'Lifestyle',
    summary: 'Fast fashion makes clothes cheap and short-lived. Slow down your wardrobe.',
    readMinutes: 3,
    sections: [
      s('What is fast fashion', 'Fast fashion means producing huge numbers of cheap, trendy clothes quickly, so styles change every few weeks. People buy more and wear each piece fewer times, and a lot ends up in the bin after only a handful of uses.'),
      s('The costs', 'Making clothes uses large amounts of water and energy, and dyeing and finishing can pollute rivers if wastewater is not treated. Polyester and other synthetic fabrics come from fossil fuels and shed microplastics when washed. Discarded textiles pile up in landfills or are burned.'),
      s('Slow it down', 'Buy fewer, better-made pieces you will wear often, repair buttons and hems, swap or buy secondhand, and donate or upcycle old clothes into rags and bags. Washing less, in cold water, and air-drying also extend the life of clothes.'),
    ],
    takeaway: 'Wear what you have more often: cost per wear is the real price of a garment.',
    quiz: [
      q('What does fast fashion produce?', 'Cheap trendy clothes in huge numbers', ['Clothes made to last decades', 'Only winter wear', 'Only school uniforms'], 'Quantity and speed define fast fashion.'),
      q('What can pollute rivers in clothing production?', 'Untreated dye wastewater', ['Clean cotton', 'Sunlight', 'Wind'], 'Dyes and finishing chemicals can contaminate water.'),
      q('Which fabric comes from fossil fuels?', 'Polyester', ['Cotton', 'Linen', 'Jute'], 'Polyester is a petroleum-based synthetic.'),
      q('Which habit helps clothes last longer?', 'Repairing and washing less', ['Washing daily', 'Tumble-drying always', 'Ironing at maximum'], 'Gentle care and repairs extend life.'),
      q('What is a good alternative to buying new?', 'Swapping or buying secondhand', ['Buying more trends', 'Throwing clothes after one use', 'Burning old clothes'], 'Reusing existing clothes avoids new production.'),
    ],
    sourceNote: 'UN Environment Programme and Ellen MacArthur Foundation summaries of textile impacts.',
  },
  {
    key: 'greener_travel',
    title: 'Travelling Lighter on the Planet',
    emoji: '🚆',
    tag: 'Travel',
    summary: 'Holidays and long trips: how to pick lower-carbon ways to go and to stay.',
    readMinutes: 3,
    sections: [
      s('How you go', 'Per passenger and per kilometre, flying produces much more greenhouse gas than trains, and trains usually produce less than cars. Indian Railways has electrified most of its broad-gauge network and has set a goal of reaching net zero emissions by 2030, so taking the train is typically the greener long-distance choice.'),
      s('Where you stay and what you do', 'Pick places that manage waste and water well, support local guides and homestays, and favour experiences that do not harm nature. Avoid disturbing wildlife, never feed animals, and stay on marked paths so you do not trample fragile habitats.'),
      s('Travel kit', 'Carry a reusable bottle, bag and cutlery, since tourist spots often have mountains of plastic. Take your litter with you if there are no bins, and leave places cleaner than you found them. A slower trip with fewer stops often means less carbon and more enjoyment.'),
    ],
    takeaway: 'Choose trains over planes when you can, and take only photos and memories.',
    quiz: [
      q('Which usually has lower emissions per passenger for long trips in India?', 'Train', ['Private jet', 'Solo car trip', 'Helicopter'], 'Trains are generally the greener long-distance option.'),
      q('Indian Railways aims for net zero emissions by when?', '2030', ['1990', '2005', '2100'], 'It has announced a target of net zero by 2030.'),
      q('What should you carry to cut plastic when travelling?', 'A reusable bottle and bag', ['Single-use cups', 'Plastic straws', 'Disposable cutlery'], 'Reusables avoid waste at tourist spots.'),
      q('What is good practice on a nature trail?', 'Stay on marked paths', ['Pick plants', 'Feed animals', 'Leave rubbish'], 'Keeping to paths protects habitats.'),
      q('What should you do with litter where there are no bins?', 'Carry it out with you', ['Bury it', 'Burn it', 'Drop it'], 'Leave no trace.'),
    ],
    sourceNote: 'Indian Railways electrification and net-zero announcements; general transport-emissions comparisons.',
  },
  {
    key: 'community_power',
    title: 'The Power of Doing It Together',
    emoji: '🤝',
    tag: 'Community',
    summary: 'Neighbourhood action that outperforms any one household.',
    readMinutes: 3,
    sections: [
      s('Why together works', 'Many problems, like waste collection, lakes, street trees and bus routes, can only be fixed at the neighbourhood or city level. A group can set up composting for a whole society, run a clean-up, or ask the local body for better services, and it can do things one family cannot.'),
      s('Ways to join in', 'Start with your resident welfare association: propose waste segregation, rainwater harvesting or solar for common areas. Join or create tree-planting and lake clean-up drives with local NGOs, record birds and plants in citizen-science projects such as eBird, and help neighbours who are new to sorting waste.'),
      s('Using your voice', 'Report broken streetlights, overflowing bins and illegal dumping to your municipal helpline, attend ward meetings, and vote for local representatives who take environment seriously. Collective pressure is how many cities got better bus services, parks and waste rules.'),
    ],
    takeaway: 'Pick one local group or problem and show up regularly: collective action changes systems.',
    quiz: [
      q('Why do neighbourhood groups matter?', 'They can fix problems one household cannot', ['They stop all rain', 'They replace government', 'They only meet in winter'], 'Shared problems need shared solutions.'),
      q('What could a resident welfare association start?', 'Waste segregation or composting', ['A traffic jam', 'A plastic dump', 'A noisy party every night'], 'RWAs can organise society-wide programmes.'),
      q('What is citizen science?', 'Public volunteers recording nature data', ['Only scientists in labs', 'A shopping app', 'A tax'], 'Projects like eBird use public observations.'),
      q('Where can you report a broken streetlight or overflowing bin?', 'The municipal helpline', ['A bakery', 'A cinema', 'A fuel pump'], 'Local bodies handle civic complaints.'),
      q('What helps cities get better services over time?', 'Collective pressure and civic participation', ['Silence', 'Littering', 'Avoiding all meetings'], 'Organised citizen voices drive change.'),
    ],
    sourceNote: 'General civic-engagement guidance; eBird citizen-science programme.',
  },
  {
    key: 'what_one_person_can_do',
    title: 'What One Person Can Really Do',
    emoji: '🌍',
    tag: 'Community',
    summary: 'Avoid eco-guilt and eco-despair: focus on the actions that add up and spread.',
    readMinutes: 3,
    sections: [
      s('Your actions are real, but not the whole story', 'Big emissions come from power plants, factories, transport systems and food supply chains, so changing systems matters. But systems are made of choices, rules and votes, and individuals shape all three. Doing your part and pushing for better rules are not in conflict.'),
      s('Choose the high-impact few', 'Rather than trying to be perfect, pick a few actions that matter: use less energy and switch to clean power if you can, move around smartly, waste less food, buy less and buy to last, and plant and protect trees and green spaces. Do them consistently.'),
      s('Spread it', 'Habits are contagious. When you carry a bottle, sort your waste or cycle to work, others notice and copy you. Talk about what you do without preaching, bring friends along to drives and clean-ups, and celebrate progress. A small step taken by many people makes a very large difference.'),
    ],
    takeaway: 'Do a few things well, keep going, and bring others with you.',
    quiz: [
      q('Why do individual actions still matter?', 'They shape choices, rules and votes', ['They never matter', 'They replace all policy', 'They only matter in cities'], 'Systems are built from individual and collective decisions.'),
      q('What is a sensible approach to personal action?', 'Pick a few high-impact habits and keep them up', ['Try to be perfect at everything', 'Give up', 'Wait for others'], 'Consistency beats perfection.'),
      q('Which is a high-impact area for most people?', 'Energy and transport', ['The colour of your clothes', 'The shape of your plate', 'The time you wake up'], 'Energy and transport are among the biggest sources.'),
      q('How do habits spread?', 'Others notice and copy you', ['They never spread', 'Only through TV', 'Only by force'], 'People follow what they see around them.'),
      q('What is a helpful attitude about progress?', 'Celebrate small steps by many people', ['Ignore small steps', 'Only large steps count', 'Blame others'], 'Small steps multiplied across a community add up.'),
    ],
    sourceNote: 'Synthesis of climate-communication research on individual and collective action.',
  },
];
