import { SeedLesson, q, s } from './lessonHelpers';

export const LESSONS_2: SeedLesson[] = [
  {
    key: 'e_waste_basics',
    title: 'E-Waste: Your Old Phone Is Not Trash',
    emoji: '📱',
    tag: 'Waste',
    summary: 'Old gadgets hold both toxic materials and valuable metals. Here is how to dispose of them well.',
    readMinutes: 3,
    sections: [
      s('What counts as e-waste', 'Phones, laptops, chargers, batteries, TVs, tube lights and other electrical items become e-waste when they stop being used. India is among the largest producers of e-waste in the world, and the amount grows every year as gadgets are replaced faster.'),
      s('Poison and treasure', 'Electronics can contain lead, mercury and cadmium, which are harmful if they leak into soil and water or are released by burning. The same devices also contain copper, gold, silver and other metals that can be recovered, which saves mining new ones.'),
      s('What to do with it', 'India\'s E-Waste (Management) Rules make producers responsible for collecting and recycling what they sell. Hand old devices to an authorised recycler or a brand take-back or exchange programme, or donate working ones. Avoid selling to roadside scrap buyers who burn wires to get at the copper.'),
    ],
    takeaway: 'Never bin old electronics: repair, donate, or give them to an authorised recycler.',
    quiz: [
      q('Which of these counts as e-waste?', 'A dead phone charger', ['A banana peel', 'A glass jar', 'A cardboard box'], 'Any discarded electrical or electronic item is e-waste.'),
      q('Which hazardous material can electronics contain?', 'Lead', ['Salt', 'Sugar', 'Oxygen'], 'Lead, mercury and cadmium are among the toxic materials.'),
      q('Why is recycling e-waste valuable?', 'Metals can be recovered', ['It makes more plastic', 'It makes electricity free', 'It stops all gadgets breaking'], 'Recovered metals reduce the need for new mining.'),
      q('What should you avoid doing with old wires?', 'Burning them to get the copper', ['Donating them', 'Handing them to a recycler', 'Reusing them'], 'Burning releases toxic fumes.'),
      q('Who is responsible for collecting e-waste under India\'s rules?', 'The producers, through extended responsibility', ['Only the buyer', 'Only the government', 'No one'], 'Producers must set up take-back and recycling.'),
    ],
    sourceNote: 'E-Waste (Management) Rules, 2022; Global E-waste Monitor.',
  },
  {
    key: 'wetlands_sponges',
    title: 'Wetlands: A City\'s Natural Sponges',
    emoji: '🦆',
    tag: 'Water',
    summary: 'Lakes and marshes soak up floods, clean water and cool cities, so why do we fill them in?',
    readMinutes: 3,
    sections: [
      s('What wetlands do', 'Wetlands such as lakes, ponds, marshes and mangroves hold water in the monsoon and release it slowly. They recharge groundwater, filter pollutants, give homes to birds and fish, and cool the surrounding area.'),
      s('When they disappear', 'When wetlands are filled for roads and buildings, rain has nowhere to go. Many Indian cities that have lost lakes and marshes have seen more severe flooding, and Chennai\'s 2015 floods are widely linked to the loss of wetlands and the blocking of natural drainage.'),
      s('How to help', 'Support local lake clean-ups, never dump waste or construction debris near water bodies, and speak up when a lake or pond is threatened. World Wetlands Day on 2 February is a good moment to visit or adopt a local water body.'),
    ],
    takeaway: 'Protect nearby lakes and marshes; they are cheaper and more effective flood defences than concrete drains.',
    quiz: [
      q('How do wetlands help during heavy rain?', 'They hold water and release it slowly', ['They make more rain', 'They heat the water', 'They block all water'], 'They act like sponges.'),
      q('What else do wetlands do?', 'Recharge groundwater and filter pollutants', ['Create plastic', 'Absorb all sound', 'Remove all trees'], 'They support clean water and wildlife.'),
      q('Why can filling in a lake increase flooding?', 'Rain has nowhere to be stored', ['Lakes cause floods', 'It makes the ground dry', 'It stops rain'], 'Without storage, runoff swamps streets.'),
      q('Which day is World Wetlands Day?', '2 February', ['5 June', '22 April', '1 January'], 'World Wetlands Day is observed on 2 February.'),
      q('Which action protects a nearby lake?', 'Joining a clean-up and not dumping waste', ['Dumping debris on the edge', 'Draining it', 'Burning waste near it'], 'Clean-ups and no dumping keep wetlands healthy.'),
    ],
    sourceNote: 'Ramsar Convention on Wetlands; widely reported analyses of the 2015 Chennai floods.',
  },
  {
    key: 'weather_vs_climate',
    title: 'Weather vs Climate: Why a Cold Day Doesn\'t Disprove Warming',
    emoji: '🌡️',
    tag: 'Climate',
    summary: 'A simple way to tell the two apart, and how the planet is changing.',
    readMinutes: 3,
    sections: [
      s('Short vs long', 'Weather is what is happening today: rain, heat, wind. Climate is the pattern averaged over many years, usually 30 or more. A single cold winter day is weather. A steady rise in average temperatures over decades is climate.'),
      s('The greenhouse effect', 'Gases such as carbon dioxide and methane trap heat in the atmosphere. This natural effect keeps Earth warm enough for life, but burning coal, oil and gas and cutting forests have added extra gases, so more heat is trapped.'),
      s('What has changed', 'Global average temperature has risen by about 1.1 degrees Celsius since the late 1800s. This shows up as more intense heat waves, heavier downpours, stronger cyclones and sea level rise. Small changes in the average mean big changes at the extremes.'),
    ],
    takeaway: 'Weather changes by the hour; climate changes by the decade, and the trend is warming.',
    quiz: [
      q('Which describes climate rather than weather?', 'The average rainfall over 30 years', ['Rain this afternoon', 'Tomorrow\'s forecast', 'Today\'s heat'], 'Climate is long-term averages.'),
      q('Which gas traps heat in the atmosphere?', 'Carbon dioxide', ['Argon', 'Helium', 'Neon'], 'Carbon dioxide and methane are greenhouse gases.'),
      q('Roughly how much has global temperature risen since the late 1800s?', 'About 1.1 degrees Celsius', ['About 11 degrees', 'About 0.01 degrees', 'It has fallen'], 'About 1.1 degrees Celsius according to major climate assessments.'),
      q('What helps cause the extra greenhouse gases?', 'Burning fossil fuels', ['Walking', 'Planting trees', 'Drying clothes in the sun'], 'Coal, oil and gas release carbon dioxide.'),
      q('Which is an expected effect of a warming climate?', 'More intense heat waves', ['Fewer storms everywhere', 'No change in rain', 'Lower sea level'], 'Extremes become more frequent and intense.'),
    ],
    sourceNote: 'IPCC Sixth Assessment Report (AR6), Summary for Policymakers.',
  },
  {
    key: 'eat_local_seasonal',
    title: 'Seasonal Food and the Millet Comeback',
    emoji: '🌾',
    tag: 'Food',
    summary: 'What is in season, what is local, and why millets are climate-friendly crops.',
    readMinutes: 3,
    sections: [
      s('Why seasonal', 'Food grown in its natural season usually needs less artificial heating, cooling, storage and long-distance transport. It is often fresher, cheaper and tastier too. Local markets and farmers\' markets make seasonal eating easy.'),
      s('A myth about food miles', 'Transport is not always the biggest part of a food\'s footprint. For many foods, how it is grown matters more, and meat and dairy generally have a larger footprint than plant foods, whether local or not. Eating more plants and wasting less often beats just buying local.'),
      s('Why millets', 'Millets such as ragi, bajra and jowar need less water and tolerate heat and poor soil better than rice or wheat, so they are well suited to a changing climate. The United Nations marked 2023 as the International Year of Millets, a proposal led by India.'),
    ],
    takeaway: 'Eat more plants, more seasonally and more millets, and waste less.',
    quiz: [
      q('Why can seasonal food be better for the planet?', 'It needs less artificial heating and storage', ['It is always imported', 'It uses more fuel', 'It is always cheaper'], 'Growing in season avoids energy-hungry shortcuts.'),
      q('What often matters more than distance for a food\'s footprint?', 'How it is produced', ['The colour of the label', 'The shape of the pack', 'The day of the week'], 'Production methods and food type often dominate.'),
      q('Which crops are known for needing less water?', 'Millets', ['Sugarcane', 'Rice paddy', 'Water chestnuts'], 'Millets are hardy and drought-tolerant.'),
      q('Which is a millet?', 'Ragi', ['Basmati', 'Maida', 'Sugar'], 'Ragi (finger millet), bajra and jowar are millets.'),
      q('Which year did the UN mark as the International Year of Millets?', '2023', ['1990', '2005', '2040'], 'The year 2023 was declared International Year of Millets.'),
    ],
    sourceNote: 'FAO and UN General Assembly resolution on the International Year of Millets 2023.',
  },
  {
    key: 'urban_heat',
    title: 'Why Cities Run Hotter',
    emoji: '🏙️',
    tag: 'Climate',
    summary: 'Concrete traps heat. Shade, trees and light-coloured roofs help cool the city.',
    readMinutes: 3,
    sections: [
      s('The heat island effect', 'Cities are often several degrees hotter than nearby countryside, especially at night. Dark roads and roofs absorb sunlight and release it slowly, there is little vegetation to shade the ground, and air conditioners, vehicles and machines add waste heat. This is called the urban heat island effect.'),
      s('Who suffers most', 'Heat waves are especially dangerous for outdoor workers, children, the elderly and families living under tin or concrete roofs with poor ventilation. Hotter nights make it harder for the body to recover, and cooling uses more electricity, which in turn adds more emissions.'),
      s('What helps', 'Trees and green cover give shade and cool the air as they release water vapour. Painting roofs white or using reflective coatings ("cool roofs") can lower indoor temperatures. Open spaces, water bodies and light-coloured paving also help. At home, curtains, shaded windows and plants on balconies cut heat.'),
    ],
    takeaway: 'Shade, greenery and light-coloured roofs make cities cooler and cut the demand for air conditioning.',
    quiz: [
      q('What is the urban heat island effect?', 'Cities being hotter than their surroundings', ['Islands near cities', 'Cold air in cities', 'A type of cyclone'], 'Built-up areas trap and store heat.'),
      q('Why do dark roofs make a city hotter?', 'They absorb a lot of sunlight', ['They reflect all sunlight', 'They block all heat', 'They make shade'], 'Dark surfaces soak up and release heat.'),
      q('Which can help lower roof temperatures?', 'White or reflective coatings', ['Black paint', 'Metal sheets uncovered', 'Plastic covers'], 'Cool roofs reflect sunlight.'),
      q('How do trees cool the air?', 'Shade and releasing water vapour', ['By burning fuel', 'By absorbing all light', 'By making wind'], 'They shade the ground and cool through evaporation.'),
      q('Who is most at risk during heat waves?', 'Outdoor workers and the elderly', ['Only athletes', 'Only people in cold places', 'No one'], 'People with less ability to avoid heat are most at risk.'),
    ],
    sourceNote: 'General urban climate research; heat action plans by Indian city authorities.',
  },
  {
    key: 'tiny_plastics',
    title: 'Microplastics: The Plastic You Can\'t See',
    emoji: '🔬',
    tag: 'Waste',
    summary: 'Plastic breaks into tiny bits that travel through water, food and air.',
    readMinutes: 3,
    sections: [
      s('What they are', 'Microplastics are plastic particles smaller than 5 millimetres. Some are made that small, like the beads once used in scrubs; most come from larger plastic items that crack and crumble, from tyre wear, and from synthetic clothes that shed fibres in the wash.'),
      s('Where they travel', 'Microplastics have been found in rivers, oceans, soil, drinking water, table salt and even the air. Studies have detected them in human blood and organs. The health effects are still being researched, but because plastic does not break down fully, they accumulate over time.'),
      s('Cutting down', 'Wash synthetic clothes less often and in full loads, use a laundry filter bag, choose natural fabrics like cotton and linen when you can, avoid products with plastic microbeads, and cut single-use plastic so less ends up fragmenting in the environment.'),
    ],
    takeaway: 'Less plastic in means fewer microplastics out, so reduce at the source and wash synthetics gently.',
    quiz: [
      q('How small are microplastics?', 'Under 5 millimetres', ['About 1 metre', 'About 30 centimetres', 'About 5 centimetres'], 'They are tiny plastic particles under 5 mm.'),
      q('Where can microplastics come from?', 'Synthetic clothes shedding in the wash', ['Fresh vegetables only', 'Clouds only', 'Stainless steel'], 'Washing releases tiny synthetic fibres.'),
      q('Where have microplastics been found?', 'Oceans, soil and drinking water', ['Only on mountain tops', 'Only in factories', 'Nowhere'], 'They have spread through nearly every environment studied.'),
      q('What helps reduce microplastic pollution?', 'Using less single-use plastic', ['Burning plastic', 'Buying more synthetic items', 'Washing every day'], 'Reducing plastic cuts what can fragment.'),
      q('Which fabric sheds fewer plastic fibres?', 'Cotton', ['Polyester', 'Nylon', 'Acrylic'], 'Natural fibres do not shed plastic.'),
    ],
    sourceNote: 'UN Environment Programme; peer-reviewed microplastics research. Health effects are still being studied.',
  },
  {
    key: 'repair_and_reuse',
    title: 'Repair, Reuse, Rethink',
    emoji: '🧵',
    tag: 'Lifestyle',
    summary: 'The greenest product is the one you already own. Make it last.',
    readMinutes: 3,
    sections: [
      s('The waste hierarchy', 'The popular rule is reduce, reuse, recycle, in that order. Recycling still needs energy and often turns items into lower-quality material, so using less and using things longer is better than recycling more.'),
      s('Where the footprint is', 'For many products, most of the environmental impact comes from making them, not using them. The majority of a smartphone\'s lifetime carbon footprint is created in manufacturing, so keeping a phone for an extra year or two does more than almost any other action.'),
      s('A culture of fixing', 'India has a strong tradition of repair: tailors, cobblers, electricians and appliance repair shops. Using them keeps things in use and supports local work. Ask about repair before replacing, borrow or rent what you will use rarely, and pass on, swap or donate what you no longer need.'),
    ],
    takeaway: 'Repair first, buy secondhand where you can, and keep devices a little longer.',
    quiz: [
      q('In "reduce, reuse, recycle", which comes first?', 'Reduce', ['Recycle', 'Burn', 'Throw'], 'Using less prevents waste in the first place.'),
      q('For many gadgets, where does most of the carbon footprint come from?', 'Manufacturing', ['Charging', 'Packaging', 'Advertising'], 'Making the device is the biggest part.'),
      q('What is a good first step before replacing a broken item?', 'Ask whether it can be repaired', ['Throw it away', 'Burn it', 'Hide it'], 'Repair extends life and avoids new production.'),
      q('Which action supports reuse?', 'Swapping or donating things you no longer need', ['Binning working items', 'Buying duplicates', 'Breaking items on purpose'], 'Passing items on keeps them in use.'),
      q('Why is keeping a phone longer helpful?', 'It avoids the emissions of making a new one', ['It makes the battery new', 'It reduces its weight', 'It lowers the screen size'], 'Fewer new devices means fewer manufacturing emissions.'),
    ],
    sourceNote: 'Manufacturer lifecycle reports and waste-hierarchy guidance; figures vary by product.',
  },
  {
    key: 'noise_pollution',
    title: 'Noise: The Pollution We Ignore',
    emoji: '🔊',
    tag: 'Community',
    summary: 'Loud sound harms sleep, health and wildlife, and there are rules about it.',
    readMinutes: 3,
    sections: [
      s('How loud is too loud?', 'Sound is measured in decibels (dB). Long exposure to sound above about 85 dB, like heavy traffic, loud speakers or a noisy workshop, can damage hearing. Even lower constant noise raises stress, disturbs sleep and affects concentration and heart health.'),
      s('The rules in India', 'The Noise Pollution (Regulation and Control) Rules, 2000 set limits for different zones. For residential areas the limit is 55 dB in the daytime and 45 dB at night, and loudspeakers and public address systems are restricted at night, generally between 10 pm and 6 am. Silence zones near hospitals, courts and schools are stricter.'),
      s('Quiet is a community habit', 'Avoid unnecessary honking, keep music and TV at reasonable volumes, especially at night, and plan loud celebrations with neighbours in mind. Animals and birds are disturbed by noise too. If noise is persistently over the limit, you can complain to the local police or pollution control board.'),
    ],
    takeaway: 'Lower the volume and the honking: quiet protects health, sleep and wildlife.',
    quiz: [
      q('What unit measures sound level?', 'Decibel', ['Kilogram', 'Volt', 'Litre'], 'Sound is measured in decibels (dB).'),
      q('Long exposure above about what level can damage hearing?', '85 dB', ['20 dB', '35 dB', '5 dB'], 'Roughly 85 dB and above over long periods can harm hearing.'),
      q('What is the daytime limit for residential areas under India\'s rules?', '55 dB', ['25 dB', '95 dB', '115 dB'], 'The limit is 55 dB by day and 45 dB at night.'),
      q('Which is a silence zone?', 'Near a hospital', ['A railway track', 'A factory floor', 'A market stall'], 'Areas near hospitals, schools and courts are silence zones.'),
      q('How can you reduce noise in your community?', 'Avoid unnecessary honking', ['Honk more', 'Play music louder at night', 'Ignore it'], 'Small habits like less honking help everyone.'),
    ],
    sourceNote: 'Noise Pollution (Regulation and Control) Rules, 2000; WHO guidance on environmental noise.',
  },
  {
    key: 'green_festivals',
    title: 'Celebrating Without the Waste',
    emoji: '🪔',
    tag: 'Community',
    summary: 'Festivals can be joyful and kind to rivers, air and neighbours.',
    readMinutes: 3,
    sections: [
      s('Idols and water', 'Ganesh and Durga idols made from Plaster of Paris and painted with chemical colours do not dissolve easily and can harm lakes and rivers when immersed. Idols made of natural clay (shadu mati) with natural colours dissolve safely. Many cities offer artificial immersion tanks or collection points.'),
      s('Light, colours and sound', 'Firecrackers raise fine-particle pollution and noise sharply around Diwali, harming people with asthma, the elderly, children and animals. Diyas, string lights, rangoli with flower petals and rice flour are lower-impact alternatives. For Holi, choose natural, skin-safe colours and save water.'),
      s('Flowers and waste', 'Temple flowers, garlands and food offerings can be composted instead of being dumped into rivers. Choose cloth or leaf decorations over thermocol and plastic, share leftover festive food, and reuse decorations next year.'),
    ],
    takeaway: 'Choose clay idols, natural colours and fewer crackers: the festival feels just as bright.',
    quiz: [
      q('Which is the better idol material for immersion?', 'Natural clay', ['Plaster of Paris', 'Plastic', 'Thermocol'], 'Clay dissolves safely; Plaster of Paris does not.'),
      q('What do firecrackers sharply increase?', 'Fine-particle air pollution', ['Rainfall', 'Oxygen', 'Tree growth'], 'They release smoke and particles.'),
      q('Which is a low-impact decoration?', 'Flower-petal rangoli', ['Thermocol', 'Plastic sheets', 'Tinsel from plastic'], 'Natural materials can be composted.'),
      q('What should happen to temple flowers?', 'Be composted', ['Dumped in a river', 'Burned', 'Buried with plastic'], 'Composting returns nutrients to soil.'),
      q('Why do natural Holi colours matter?', 'They are safer for skin and water', ['They are heavier', 'They never wash out', 'They are always blue'], 'Chemical colours can irritate skin and pollute.'),
    ],
    sourceNote: 'CPCB guidelines on idol immersion; general festival-pollution guidance.',
  },
  {
    key: 'bees_and_butterflies',
    title: 'Why Your Food Needs Bees (and Bats and Butterflies)',
    emoji: '🐝',
    tag: 'Nature',
    summary: 'A big share of the crops we eat depends on pollinators, and they are in trouble.',
    readMinutes: 3,
    sections: [
      s('What pollinators do', 'Bees, butterflies, moths, beetles, birds and bats carry pollen from flower to flower so plants can make fruit and seeds. Roughly three-quarters of the leading food crop types benefit at least partly from animal pollination, including many fruits, vegetables, oilseeds and nuts.'),
      s('Why they are declining', 'Pollinators are threatened by habitat loss, heavy use of pesticides, disease and climate change. When farms and cities leave little space for flowers, pollinators lose both food and nesting places.'),
      s('Make space', 'Grow flowering plants on a balcony, garden or school yard, ideally native ones that bloom at different times. Avoid chemical pesticides, leave a patch of wild or bare soil, and keep a shallow dish of water with stones for landing. Support local honey and organic farmers.'),
    ],
    takeaway: 'A few pots of flowers and no pesticides can turn a balcony into a pollinator stop.',
    quiz: [
      q('What do pollinators do?', 'Move pollen between flowers', ['Make rain', 'Clean rivers', 'Cut trees'], 'This allows plants to make fruit and seeds.'),
      q('Which of these is a pollinator?', 'A butterfly', ['A rock', 'A cloud', 'A river'], 'Butterflies, bees, moths, birds and bats all pollinate.'),
      q('Roughly what share of leading food crop types benefit from animal pollination?', 'About three-quarters', ['None', 'About 5 percent', 'All of them need none'], 'Most major crop types benefit from pollinators.'),
      q('What threatens pollinators?', 'Pesticides and habitat loss', ['Too many flowers', 'Clean air', 'Rain'], 'Both reduce their food and nesting places.'),
      q('Which action helps pollinators at home?', 'Growing flowering plants without pesticides', ['Spraying insecticide', 'Paving the garden', 'Removing all flowers'], 'Flowers give food; no pesticides keeps them safe.'),
    ],
    sourceNote: 'IPBES and FAO assessments on pollinators and food production.',
  },
];
