import { s } from './lessonHelpers';

type Section = ReturnType<typeof s>;

// Two extra sections per lesson (lessons 21-30). See lessonExtras1.ts.
export const EXTRAS_3: Record<string, Section[]> = {
  carbon_footprint_101: [
    s('Putting numbers in context', 'Electricity is a good place to start because it is easy to measure. On India\'s grid, each unit (kilowatt-hour) of electricity is associated with roughly 0.7 kilograms of carbon dioxide, because a large share still comes from coal. That means a fan, a bulb or an air conditioner that you leave on for hours has a real footprint, and the same appliance has a smaller footprint if it is efficient or if you use solar power. Vehicles, flights, cooking gas and the food you eat all have their own numbers. You do not need to calculate everything, but knowing your electricity units, your fuel use and how often you fly or drive gives a good start.'),
    s('Offsets and honest accounting', 'Carbon offsets, where you pay for trees or clean energy projects elsewhere to balance emissions, can help in some cases, but they are not a licence to keep emitting, and their quality varies a lot. Cutting your own emissions first is more reliable. Use a footprint calculator with your real bills and travel to see which area is biggest, then set one target, for example lowering your electricity use by ten percent. Remember too that your footprint depends on the systems around you, such as how clean the grid is and whether the city has good transport. Changing your habits and asking for better systems both matter.'),
  ],
  spot_greenwashing: [
    s('Common tricks', 'Researchers have identified recurring patterns. A product may highlight one green feature while ignoring a bigger harm, such as an "eco" pack inside a heavily packaged box. It may make claims with no proof, or use vague words like "natural" that have no legal meaning. It may boast of something that is already required by law, such as being free of a chemical that is banned anyway. Pictures of leaves, earth tones and green packaging create an impression with no evidence behind it. Some companies invent their own seals that look official. When a company spends more on advertising its green image than on changing how it works, be wary.'),
    s('How to check a claim', 'Look for specific, measurable statements such as the percentage of recycled content, and for independent certification that you can look up: in India, examples include the BIS Ecomark and the BEE star label for appliances. Check whether the company publishes its emissions and targets and reports progress honestly. Compare the product with simpler alternatives, and ask if you need it at all. India\'s advertising watchdog, ASCI, has guidelines on environmental claims in advertisements and accepts complaints about misleading ones. Asking questions politely, on a brand\'s social media or customer care, also pushes companies to be more honest.'),
  ],
  plastic_free_kitchen: [
    s('Materials that last', 'Stainless steel, glass, ceramic, cast iron, wood and clay are durable, safe for cooking and storing, and can be used for decades. Traditional options are still around: earthen matkas that cool water, banana leaves and sal-leaf plates, brass or copper vessels, and cotton cloth for covering food. Replace scratched or cracked non-stick pans and old plastic containers when they wear out. Even containers marked "microwave safe" will age and may release particles with repeated heating. You do not have to throw away the plastic you own: use it until it is worn, then replace it with something longer-lasting.'),
    s('Shopping and storing smarter', 'Buy staples like rice, atta, pulses and spices loose or in the largest practical pack, and carry your own cloth bags and containers. Some shops will fill your box with milk products, sweets or meat if you ask. Reuse glass jars from pickles and jam, cover bowls with plates instead of cling film, and wrap bread and vegetables in cloth. Keep a list of where to get refills near you, such as oil, detergent or cleaning liquid. Take it slowly: change one habit a month, and notice how your bin gets lighter. Share ideas with your household so that everyone is on board.'),
  ],
  our_rivers: [
    s('Progress and the long road', 'India has put large programmes in place, such as Namami Gange, launched in 2014, which funds sewage treatment plants, riverfront work and awareness along the Ganga. Some stretches have improved, but others, such as the Yamuna through Delhi, remain heavily polluted, because the amount of sewage created by growing cities is large and many drains still flow untreated into rivers. Cleaning rivers needs treatment plants that actually work, industries that treat their waste, and citizens who stop dumping. It also needs rivers to have enough water flowing, because a river with less flow cannot dilute or clean pollution.'),
    s('What your household sends downstream', 'Everything poured into drains eventually meets a river or lake. Detergents with phosphates cause foam and algae blooms that choke water bodies. Oils, paints, medicines and chemicals poison water and soil. Microplastics from laundry and cosmetics slip through treatment. Flowers, idols and plastic offerings add to the load. Choose phosphate-free or natural cleaners such as soap nuts, avoid pouring oil, and dispose of medicines and paint as hazardous waste. Check whether your home is connected to a proper sewer or a well-built septic tank. Pressing your local body for sewage treatment is one of the most powerful things you can do for a river.'),
  ],
  rooftop_solar_basics: [
    s('Size, cost and payback', 'As a rule of thumb, one kilowatt of panels needs around ten square metres of shade-free roof and produces roughly four to five units of electricity on an average sunny day in many parts of India. A 2 to 3 kilowatt system covers the needs of many homes. With subsidy and savings on bills, the cost is often paid back in a few years to less than a decade, after which electricity is almost free for the rest of the panels\' life. Your actual savings depend on your tariff, how much you use during the day, and shade. A good installer will study your last 12 bills and your roof before giving a quote.'),
    s('Choosing an installer and keeping it running', 'Use a vendor empanelled or recommended by your electricity distribution company or the national portal, ask for the panel and inverter brands, performance and product warranties, and who handles net-metering paperwork. Panels need little care: rinse off dust every few weeks, trim shading branches and watch the monitoring app for dips. Batteries add cost and are not needed for grid-connected systems, though they help in areas with frequent power cuts. If you live in an apartment, ask your housing society about solar for lifts and common lights, or about community solar. A solar water heater is a cheap, reliable first step too.'),
  ],
  living_with_wildlife: [
    s('Different regions, different challenges', 'In parts of Kerala, Karnataka, Assam and Jharkhand, elephants raid crops and sometimes enter villages. In Maharashtra and near Mumbai\'s Sanjay Gandhi National Park, leopards live close to people. Monkeys are common in many towns, and snakes appear in the monsoon when burrows flood. Communities have found workable solutions: beehive fences that elephants avoid, chilli-based barriers, early-warning alerts by phone, safe storage of grain and waste, and compensation for farmers. If you meet a snake, keep away and call a trained rescuer or the forest department instead of killing it, since most snakes in India are harmless and they control rats.'),
    s('Why predators and forests matter', 'Large predators like tigers sit at the top of food chains, and protecting them also protects the forests, rivers and countless other species in their habitat. Many of India\'s major rivers begin in forests that tiger reserves protect, so conservation also means water security. Wildlife also supports tourism and jobs. Living with wildlife has a long tradition in India, through sacred groves and respect for animals, and modern ideas like shared grazing rules, wildlife corridors and community patrols build on it. Respect, distance and patience keep both people and animals safer.'),
  ],
  fast_fashion: [
    s('A sense of scale', 'The amount of clothing produced worldwide roughly doubled between 2000 and 2015, while the number of times each garment is worn went down. Less than one percent of the material used to make clothes is recycled into new clothes. Clothes also lose their shape or colour faster when they are made cheaply, and this encourages people to replace them. Behind a very low price there are costs that the buyer does not see: workers paid little, rivers polluted by dye, and large amounts of unsold stock that is thrown away. Paying a bit more for something that lasts, or not buying at all, is usually cheaper in the end.'),
    s('India\'s reuse traditions', 'India is a major producer of textiles and has a long tradition of natural fibres, handlooms and khadi. It also has strong habits of mending and reusing: tailors alter and repair clothes, old saris become kantha quilts, dupattas and bags, and clothes are passed down. Panipat in Haryana is known for recycling used clothes into yarn and blankets. You can build on this by buying handloom or durable pieces, using a tailor to alter and mend, joining clothes swaps, and turning worn-out cloth into cleaning rags or bags. Looking after your clothes is a quiet but powerful environmental act.'),
  ],
  greener_travel: [
    s('Comparing journeys', 'For many routes, a train produces a small fraction of the emissions of the same journey by plane, and a night train also saves a hotel night. Buses and shared cabs beat single-occupancy cars. When flying is unavoidable, choose direct flights, which use less fuel than ones with stopovers, travel light, and fly less often but stay longer. Think about the whole trip: local transport at the destination, food, and stays. Also consider closer destinations. A holiday within your state or region can be rich in culture and nature, and it saves both money and emissions.'),
    s('Leaving a good footprint', 'Choose homestays and small local businesses, buy crafts made locally, and respect local customs and water use, which can be scarce in tourist areas. In the mountains, carry your waste back down; plastic left on trekking routes does not break down in the cold. Follow rules in national parks, keep quiet, and never feed or crowd animals. Be wary of attractions that use animals for entertainment. Reuse towels and sheets, switch off lights and air conditioning when leaving, and take your own bottle, bag and cutlery. A good trip leaves a place as clean as you found it, or better.'),
  ],
  community_power: [
    s('Examples that worked', 'Indore has topped India\'s national cleanliness survey for several years in a row, largely because households separated waste and the city built a system around it. Citizen groups have revived lakes in Bengaluru and Chennai, and Pune\'s waste-picker cooperative SWaCH provides door-to-door collection. In many villages, community forests and water committees have restored land and wells. None of these needed perfect conditions. They began with a few committed people, a clear problem, and a willingness to work with local authorities. Change at the community level is slow but it tends to last, because people feel ownership of it.'),
    s('How to start a drive', 'Pick one clear, achievable goal, such as cleaning a lane, planting and caring for twenty saplings, or starting composting in your building. Gather five or six friends or neighbours, talk to the resident association or local body for permission and support, and arrange gloves, bags and a way to dispose of what you collect. Take before-and-after photos, thank everyone, and share the results. Plan a regular schedule, such as the first Sunday of every month, because small repeated drives beat one big event. Invite children and elders, and keep it enjoyable with tea and music so that people come back.'),
  ],
  what_one_person_can_do: [
    s('Between guilt and despair', 'It is easy to feel that your actions are too small, or to feel guilty for not being perfect. Neither helps. Climate change is mostly driven by the way energy, transport, industry and food systems work, and governments and companies have a large role in changing them. But those institutions respond to what people buy, vote for and demand. Your choices change what shops stock, your example changes what friends do, and your voice changes what leaders prioritise. Doing your part and asking for bigger change are two sides of the same effort, and both are worth doing.'),
    s('A simple ladder of action', 'Start at home with a few habits such as saving energy, wasting less food, sorting waste and walking or taking transit. Then involve your household and friends. Next, act where you spend your time: at school, college, or work, you can propose recycling, solar, or greener travel policies. Then use your civic voice by reporting problems, attending ward meetings, voting, and supporting groups that work on the environment. Money counts too: choose banks, funds and employers carefully, and donate to causes you trust. You do not have to climb every rung at once. Pick the next one that fits your life and keep going.'),
  ],
};
