import { s } from './lessonHelpers';

type Section = ReturnType<typeof s>;

// Two extra sections per lesson (lessons 11-20). See lessonExtras1.ts.
export const EXTRAS_2: Record<string, Section[]> = {
  e_waste_basics: [
    s('What is inside your phone', 'A phone contains copper, gold, silver, palladium, lithium, cobalt and many other materials, which are mined at a high environmental and human cost. A tonne of old phones holds far more gold than a tonne of gold ore, which is why recovering metals from e-waste is called "urban mining". Lithium-ion batteries need special care: if they are crushed or damaged in a garbage truck or bin, they can overheat and start fires. Never put batteries or power banks in ordinary waste, and never try to open them. Hand them over to a battery collection point or authorised recycler instead.'),
    s('Before you hand it over', 'Back up what you want to keep, sign out of your accounts, remove the SIM and memory card, and do a full factory reset so that your photos, messages and bank details are erased. Ask the recycler or take-back scheme how the device will be processed. If it still works, selling, donating or giving it to a relative extends its life, which is the best result environmentally. When you buy a new device, look for ones that are repairable, have replaceable batteries or long software support, and buy refurbished when you can. The greenest gadget is the one you keep for longer.'),
  ],
  wetlands_sponges: [
    s('Many kinds, many benefits', 'Wetlands include lakes, ponds, tanks, marshes, mangroves, floodplains and even paddy fields. Each winter, millions of migratory birds travel along the Central Asian Flyway to Indian wetlands such as Chilika in Odisha and Keoladeo in Rajasthan. Wetlands also provide fish, water for farms and income for communities. The East Kolkata Wetlands, a Ramsar site, are famous for treating much of the city\'s sewage naturally through fish ponds and farms, saving the city huge costs. These services are rarely counted, and often only noticed after a wetland has been lost and floods or water shortages follow.'),
    s('Threats and the law', 'Wetlands are lost to filling for construction, dumping of garbage and sewage, encroachment and diversion of the water that feeds them. In India, the Wetlands (Conservation and Management) Rules, 2017 aim to protect them, and the Ramsar Convention lists wetlands of international importance. Laws are only as strong as the people watching, so citizens\' groups matter. You can photograph and report dumping or illegal filling to your local body, support groups that restore lakes, take children on a visit, and take part in bird counts. Even a small neighbourhood pond is worth protecting, because it cools the area and recharges nearby wells.'),
  ],
  weather_vs_climate: [
    s('How we know the climate is changing', 'Many separate lines of evidence point the same way. Global average temperatures are rising. Glaciers and polar ice are shrinking. Sea levels are rising as oceans warm and ice melts. Oceans are getting warmer and more acidic. Spring comes earlier in many places. In India, heat waves have become more frequent, heavy rain now often falls in short, intense bursts, and Himalayan glaciers are retreating. The Intergovernmental Panel on Climate Change, which reviews thousands of studies, concludes that human influence has clearly warmed the planet. No single event proves climate change, but the pattern across decades does.'),
    s('Common confusions', '"It snowed today, so there is no warming." That is weather, not climate. "Carbon dioxide is natural, so it is harmless." It is natural, but burning fossil fuels has raised its level from about 280 parts per million before industry to over 420 today, far faster than natural changes. "The climate has always changed." True, but the current change is very fast and mainly caused by human activity. "The ozone hole causes global warming." The ozone layer and the greenhouse effect are separate problems. Understanding the difference helps you answer misleading claims calmly and with facts.'),
  ],
  eat_local_seasonal: [
    s('Know your seasons', 'In much of India, mangoes arrive in summer, jamun with the first monsoon showers, and guavas, amla, oranges and leafy greens in winter. Local markets stock what is in season in your area, and prices fall when supply is high. Seasonal produce is usually fresher, needs less storage, and often has more flavour and nutrients. Ask vendors what came in that morning. Eating this way also supports local farmers and traditional varieties, many of which are more suited to local weather and pests. Off-season fruit and vegetables usually come from far away or from cold stores, which use more energy.'),
    s('Plants, pulses and the plate', 'India\'s traditional diets are rich in pulses, vegetables and grains, and these have a smaller footprint than meat and dairy. Pulses even help soil by fixing nitrogen. Replacing even a few meals a week with dal, rajma or chana makes a difference. Millets add fibre and minerals, and ragi is a good source of calcium. Try cooking them in familiar ways: ragi dosa, bajra roti, jowar upma. Carry your own bag to the market, avoid plastic-wrapped produce, and compost the peels. Choosing varieties of crops that suit your region keeps food culture alive and the farmland resilient.'),
  ],
  urban_heat: [
    s('How big is the difference?', 'On a hot afternoon, the surface of a dark tar road or tin roof can be many degrees hotter than the air, and far hotter than a patch of grass or a shaded spot. At night, concrete releases the stored heat, so city nights stay warm and the body gets less rest from the heat. Indian cities have started heat action plans. Ahmedabad launched one of the first in South Asia in 2013, with early warnings, cool shelters and public awareness, and it is credited with helping lower heat-related deaths. These plans show that planning and awareness save lives, not just air conditioners.'),
    s('Designing cooler neighbourhoods', 'Cities can be cooled with more trees and shaded streets, cool roofs and light-coloured walls, parks and water bodies, and layouts that let breezes flow through. Traditional Indian architecture had many ideas: courtyards, jaalis (perforated screens), thick walls, high ceilings and light limewash. At home, cross-ventilation, external shading on west-facing windows, curtains, a layer of plants on the terrace and a reflective roof coating can reduce heat without much electricity. When glass-and-steel buildings need heavy air conditioning, they push even more heat outside. Good design makes comfort cheaper and the whole city cooler.'),
  ],
  tiny_plastics: [
    s('How they reach us', 'Microplastics enter our bodies through food, drinking water, sea salt, seafood and the dust we breathe. They are shed by clothes, tyres, paint, packaging and cosmetics. Heating food in plastic containers, or using plastic tea bags and kettles, can add more. Studies find different amounts in different products, and research on health effects is still developing, so scientists are cautious about what they claim. What is clear is that plastic does not go away, that it accumulates, and that it is much easier to prevent plastic from entering the environment than to remove it afterwards.'),
    s('Practical steps', 'Use a steel or glass bottle and avoid heating food in plastic. Wash synthetic clothes less often, in full loads and on gentle cycles, and consider a laundry filter bag or washing machine filter. Choose natural fabrics when you can. Dust with a damp cloth and vacuum with a good filter, since household dust carries fibres. Skip cosmetics and scrubs with plastic microbeads. And support rules that cut plastic at the source. It is easy to feel helpless about particles you cannot see, but every item of plastic you avoid is one that cannot break into thousands of tiny pieces.'),
  ],
  repair_and_reuse: [
    s('Your right to repair', 'In 2022, India\'s Department of Consumer Affairs launched a Right to Repair portal, where manufacturers of items such as mobiles, electronics, consumer durables, farm equipment and vehicles share repair information and spare-part details so that customers can fix things rather than replace them. Repair is good for the planet, for your wallet and for local jobs. It also keeps skills alive. Before you give up on a broken item, ask the manufacturer or a local repair shop for an estimate. If repair costs less than half of a replacement and the item is otherwise good, fixing it is usually the better choice.'),
    s('The reuse economy', 'India already has strong reuse habits: the kabadiwala who buys old newspapers and metal, hand-me-downs in families, and the culture of jugaad, or clever fixes. Build on it. Buy secondhand furniture, books and clothes, borrow or rent tools and party items you rarely use, join local swap groups or libraries of things, and sell or donate what you no longer need. Refurbished phones and laptops often work like new at a lower price. Every item that gets a second owner replaces one that would have been made new, saving the materials, water and energy that production would have used.'),
  ],
  noise_pollution: [
    s('Effects on body and wildlife', 'Noise is more than an annoyance. Constant loud sound can raise blood pressure and stress hormones, disturb sleep and make it harder for children to concentrate and learn. The World Health Organization treats environmental noise as a significant health problem. Animals suffer too: some birds sing louder or at different times to be heard, which wastes energy, and loud sounds can drive wildlife away from habitats. Because you get used to noise, you may not notice how much it affects you. Quiet moments, such as a walk in a park, can lower stress and help you recover.'),
    s('Making your area quieter', 'Honking is a major source of urban noise, and many cities have no-horn zones near hospitals and schools. Avoid unnecessary honking and ask others not to. Keep music, TV and loudspeakers low, particularly after 10 pm. Planting trees and shrubs along roads and walls helps absorb sound, and thick curtains and double-glazed windows lower noise indoors. Use headphones sensibly: a good rule is no more than 60 percent volume for no more than 60 minutes at a time. For festivals and weddings, agree on sound limits with neighbours. If problems continue, you can complain to the local police or the state pollution control board.'),
  ],
  green_festivals: [
    s('What goes into the water, soil and air', 'Idols made of Plaster of Paris take a long time to dissolve, and chemical paints on them can contain metals such as lead and mercury, which harm fish and water quality. Fireworks release smoke, fine particles and metal salts, and the noise frightens animals and unsettles people with health problems. Synthetic colours used at Holi can irritate skin and eyes. Plastic decorations and thermocol end up as litter. None of this means giving up celebration. It means choosing materials that return to nature safely, like clay, flowers, leaves, natural dyes, and cloth, and avoiding those that stay in the environment for a long time.'),
    s('Ideas that already exist', 'Many communities already celebrate more lightly. "Seed" Ganesha idols made of clay with seeds inside grow into plants after immersion in a pot. Cities provide artificial immersion tanks and collection points. Natural Holi colours can be made from palash (tesu) flowers, turmeric, beetroot and other plants. Clay diyas can be reused, and string lights last for years. Cloth, paper or leaf decorations can be stored and brought out again. Gifting a sapling, a book or a homemade sweet instead of plastic-wrapped goods is a thoughtful alternative. Teach children these traditions so that they carry them forward.'),
  ],
  bees_and_butterflies: [
    s('India\'s pollinators', 'India is home to several honeybee species, including the Indian honeybee (Apis cerana) and the giant rock bee (Apis dorsata) that builds huge combs on tall trees and cliffs. Thousands of other bees, along with hoverflies, butterflies, moths, beetles, sunbirds and bats, visit flowers and carry pollen. Many are wild and need no keeper. A single native plant in a pot may be visited by several different species in a day. Crops such as mustard, sunflower, mango, guava, cucumber and many pulses do better when pollinators are plentiful, so protecting them supports both biodiversity and farmers\' incomes.'),
    s('Make a pollinator patch', 'You do not need much space. Choose flowers that bloom at different times so there is food throughout the year, such as marigold, tulsi, hibiscus, cosmos, zinnia and local wildflowers, and prefer single-petal flowers where pollinators can reach nectar. Avoid pesticides, or use only gentle natural methods in the evening when bees are not active. Leave a small patch of leaf litter, bare soil or a dead branch for nesting. Keep a shallow dish of water with stones. If bees build a hive in an inconvenient place, call a local beekeeper or the forest department instead of destroying it.'),
  ],
};
