import { s } from './lessonHelpers';

type Section = ReturnType<typeof s>;

// Two extra sections per lesson (lessons 1-10), inserted after the core explanation and before the
// closing "Try this today". Keep claims to well-established facts; numbers are rounded.
export const EXTRAS_1: Record<string, Section[]> = {
  sort_your_waste: [
    s('Myths people believe', '"It all gets mixed in the truck anyway." In many cities, collection is now done in separate compartments or on separate days, and the rules require local bodies to collect segregated waste. If yours mixes it, that is a service failure you can report, not a reason to stop sorting. "Dirty waste is fine." Food-soaked paper and greasy plastic are hard to recycle, so give containers a quick rinse and keep wet scraps out of the dry bag. "Only rich countries recycle." In India, a huge amount of recycling already happens through an informal network of waste pickers, kabadiwalas and small dealers who depend on dry waste being clean and separate.'),
    s('The people behind the bins', 'India has lakhs of waste pickers who recover paper, plastic, metal and glass, saving cities money and keeping material out of dumps, usually without recognition or protection. Cities that include them formally do better. Pune\'s SWaCH, a cooperative of waste pickers and collectors, is a well-known example of door-to-door segregated collection run by the workers themselves. When you hand over clean, separated dry waste, you make their work safer and better paid, and you push more material toward recycling instead of the landfill. Treat your collector with respect and, if you can, thank them: this is one of the most useful environmental jobs in the city.'),
  ],
  plastic_bag_truth: [
    s('Cloth, paper or plastic? An honest comparison', 'No bag is automatically green; what matters is how many times you use it. A cloth bag takes more energy and water to make than a plastic bag, so it only comes out ahead after many uses. Studies give different numbers, from dozens to well over a hundred, depending on what is measured. Paper bags are heavier to make and transport and tear when wet. The lesson is simple: the best bag is the one you already own, used again and again. Buying a new designer tote bag you will only use twice is worse than carrying a thin bag you reuse for months. Look after your bag so that it lasts.'),
    s('Where bags end up', 'Light bags escape bins easily and are carried by wind and water. In cities they clog drains, and on land they get tangled in trees and fields. Rivers carry them to the sea, where turtles and other animals can mistake floating bags for jellyfish and swallow them, and where they slowly break into smaller pieces. Burning bags in the open is not a solution, because it releases harmful fumes. Because bags are light and low in value, waste pickers often do not collect them, which is why the best solution is not to create them. Carrying your own bag is a small act that removes a surprising amount of litter over a year.'),
  ],
  hidden_water: [
    s('Why the numbers differ', 'Water footprints are usually split into three kinds. Green water is rain stored in soil that plants use. Blue water is taken from rivers, tanks and groundwater for irrigation or industry. Grey water is the amount needed to dilute pollution to a safe level. Rice grown mainly on rain in one region has a different impact from rice irrigated with pumped groundwater in another, which is why the same crop can look very different in different studies. In India, heavy irrigation of thirsty crops in regions that already have falling water tables is one reason groundwater is under strain. Treat the figures as a way to compare foods and products, not as exact measurements.'),
    s('Small habits, big savings', 'At home, a bucket bath or short shower uses far less water than a long one, and turning off the tap while brushing or soaping saves several litres each time. A dripping tap can waste thousands of litres a year. Run washing machines and dishwashers only when full, and reuse the water from washing vegetables or from the RO reject for plants and cleaning. Beyond the tap, the biggest saving is in what you buy and eat: more pulses, vegetables and millets, less food waste, and clothes worn for years. These choices reduce the demand for water in farms and factories far away, where most of your water use actually happens.'),
  ],
  catch_the_rain: [
    s('How a rooftop system works', 'A basic system has four parts. The catchment is your roof. Gutters and downpipes carry the water. A first-flush diverter throws away the dirty first minutes of rain that wash dust and bird droppings off the roof. A filter then cleans the water before it goes to a storage tank, or to a recharge pit or well that sends it underground. Stored water is best for gardening, washing and flushing, and should be treated properly before drinking. Clean the roof and filters before each monsoon. Some cities, such as Chennai, which made harvesting compulsory for new buildings in 2003, and Bengaluru for larger plots, require it by law, and it is worth checking your local rules.'),
    s('Old wisdom, new need', 'Catching rain is an old Indian skill. Stepwells (baolis) in Gujarat and Rajasthan, johads (earthen check dams) in Rajasthan, eris (tanks) in Tamil Nadu and kunds in the desert all stored water through the dry months. In Alwar, Rajasthan, the revival of johads by community groups brought water back to villages and earned its leader, Rajendra Singh, the title "Waterman of India". The same idea works at any scale, from a village pond to a school roof. Reviving local water structures and keeping catchments clear is often cheaper and longer-lasting than pipes and pumps.'),
  ],
  vampire_power: [
    s('Which devices are the worst?', 'Set-top boxes, especially recording ones, often draw power all day. Game consoles left in instant-on mode, TVs with quick-start, and many chargers keep drawing electricity too. A router needs to stay on, but a microwave clock, a printer and a speaker on standby add up. The best way to find out is a cheap plug-in energy meter, which shows how many watts each device uses when it is "off". Many people are surprised to find that a few devices use more power asleep than a bulb does when lit. Putting them on a switched power strip is the easiest fix, and you save money as well as energy.'),
    s('Bigger savings in the same home', 'Air conditioners are usually the largest electricity user in a home. The Government of India has advised a default setting of 24 degrees Celsius, and using a fan alongside lets you feel cool at a higher setting. Clean the filters regularly, close doors and curtains, and service the unit before summer. In the kitchen, do not put hot food straight in the fridge, keep its door seals clean and do not leave the door open. A geyser with a timer or a solar water heater cuts a large part of winter bills. Each of these changes is small, but together they can lower an electricity bill noticeably.'),
  ],
  food_waste: [
    s('Storing food so it lasts', 'Keep leafy greens wrapped in a damp cloth in the fridge, and store onions and potatoes in a cool, dark, airy place, apart from each other. Freeze overripe bananas, leftover bread and extra cooked dal in portions. Follow first in, first out: move older items to the front. Cool cooked food quickly and refrigerate it within a couple of hours, and reheat it thoroughly. Learn the labels: "best before" is about quality, while "use by" is about safety. Many foods are fine to eat after the best-before date if they look and smell normal. A weekly "use it up" meal made from leftovers and ageing vegetables saves money and makes cooking creative.'),
    s('Beyond the home kitchen', 'A lot of food is also wasted at weddings, restaurants and canteens. Order smaller portions or half plates, ask for sauces on the side, and take leftovers home. Hosts can estimate guests more carefully and pass surplus food to food-rescue groups such as Robin Hood Army or Feeding India, which redistribute safe, unused food. Farmers and traders lose food too, before it ever reaches a shop, through poor storage and transport. At home, you can support this by buying "ugly" produce that tastes the same, and by choosing shops that sell imperfect or surplus items cheaply. Every meal saved is also money saved.'),
  ],
  know_your_aqi: [
    s('Why winter air is worse', 'In winter, cold air near the ground often sits under a layer of warmer air, a pattern called a temperature inversion. It acts like a lid and traps pollution close to the surface, and low wind speeds stop it from spreading out. In northern India this meets extra smoke from crop-residue burning in October and November, and from festival firecrackers, on top of year-round sources like vehicles, dust from construction and roads, industry and the burning of waste. That is why AQI often climbs sharply between October and January. During the monsoon, rain washes particles out of the air, which is why air quality is usually better then.'),
    s('Protecting yourself and your home', 'Indoor air matters as much as outdoor air. Cooking smoke, incense and mosquito coils can raise indoor particles, so use an exhaust fan or chimney and ventilate when outdoor air is cleaner. A few houseplants look nice but are not enough to clean a room, so do not rely on them. A HEPA air purifier sized for the room can help during bad spells, while keeping windows shut. Outdoors, an N95-type mask that fits well gives real protection. Children, older people and those with asthma or heart conditions should take extra care. Check the AQI before sport or walks, and choose quieter routes away from heavy traffic.'),
  ],
  single_use_plastics: [
    s('What the ban does and does not cover', 'The 2022 ban targets a specific list of items. It does not cover all plastic: carry bags are covered by thickness rules, and multi-layer packaging such as chips and biscuit wrappers is still widely used and hard to recycle. To deal with packaging, India introduced Extended Producer Responsibility guidelines in 2022, which require brands that put plastic packaging on the market to arrange for a share of it to be collected and recycled. As a shopper, you can reward brands that use less packaging, refills or returnable containers, and avoid tiny individually wrapped sachets when a larger pack will do. Enforcement varies by city, so your reports and choices still matter.'),
    s('Myths about "better" plastic', '"Biodegradable plastic fixes the problem." Many products labelled biodegradable only break down in industrial composting plants, not in a drain or a river, and they can still litter. "Paper cups are plastic-free." Most hot-drink paper cups have a thin plastic lining, which makes them hard to recycle. "Recycling will fix it." Globally, less than a tenth of all plastic ever made has been recycled, and much plastic can be recycled only once or twice. The most effective steps are to refuse the item, reuse what you have, and only then recycle. A steel bottle used for years beats any disposable, however green its label looks.'),
  ],
  home_composting: [
    s('Pick a method that suits your home', 'A simple aerobic bin or pot, as described above, works for most homes. Vermicomposting uses special composting worms (not ordinary garden earthworms) in a bin to turn scraps into rich compost quickly, and works well on a balcony if kept shaded and moist. Bokashi uses a bran mix to ferment kitchen waste, including small amounts of cooked food, in a sealed bucket; the fermented waste is then buried in soil or added to a compost pile. If you have no space, look for a community compost pit, a society-level composter or a municipal wet-waste collection that processes it. The best method is the one you will keep up.'),
    s('Troubleshooting and using your compost', 'A bad smell usually means it is too wet or has too many greens, so add dry leaves or paper and turn it. Fruit flies are a sign scraps are exposed, so cover them with a layer of browns. If it is dry and nothing happens, sprinkle some water. Finished compost is dark, crumbly and smells like forest soil, and you cannot recognise the original scraps. Mix it into potting soil or spread a layer around plants. It improves soil structure and holds moisture, which makes plants more resilient, though it is a soil conditioner and not a replacement for every nutrient. Composting also keeps food waste out of landfills, where it would produce methane.'),
  ],
  move_smarter: [
    s('Comparing the options', 'Per person and per kilometre, walking and cycling produce no emissions. Trains, metros and full buses are low-emission ways to move many people. Two-wheelers use less fuel than cars but still pollute, and cars carrying only one person are among the least efficient ways to travel. Electric vehicles produce no exhaust and are usually cleaner over their lifetime, though how much depends on how clean the electricity grid is. Air travel has the highest emissions per kilometre. Choosing the right mode for each trip, instead of one mode for all trips, makes the biggest difference, and short trips are the easiest to change.'),
    s('Making it work in real life', 'The hardest parts of public transport are often the first and last kilometre. Plan a walk, cycle or shared auto for that stretch, and use apps that show bus and metro timings. Carpool with colleagues or neighbours, and ask your employer about shuttles, flexible hours or work from home. Keep your vehicle serviced and carry a valid Pollution Under Control certificate, as a badly tuned engine can pollute much more. Beyond personal choices, you can ask your local body for safe footpaths, bus lanes and cycle tracks, because people only walk, cycle and take buses when they feel safe and the service is reliable.'),
  ],
};
